@regions =
  'adr':
    type:'water'
    neis:['alb','apu','ven','tri','ion']
  'aeg':
    type:'water'
    neis:['bul_sc','gre','con','smy','eas','ion']
  'alb':
    type:'coast'
    neis:['tri','gre','ser','adr','ion']
  'ank':
    type:'coast'
    neis:['arm','con','smy','bla']
  'apu':
    type:'coast'
    neis:['ven','nap','rom','adr','ion']
  'arm':
    type:'coast'
    neis:['smy','syr','ank','sev','bla']
  'bal':
    type:'water'
    neis:['lvn','pru','ber','kie','den','swe','bot']
  'bar':
    type:'water'
    neis:['stp_nc','nwg','nor']
  'bel':
    type:'coast'
    neis:['hol','pic','ruh','bur','eng','nth']
  'ber':
    type:'coast'
    neis:['kie','pru','sil','mun','bal']
  'bla':
    type:'water'
    neis:['bul_ec','rum','sev','arm','ank','con']
  'boh':
    type:'land'
    neis:['mun','sil','gal','vie','tyr']
  'bot':
    type:'water'
    neis:['stp_sc','swe','fin','lvn','bal']
  'bre':
    type:'coast'
    neis:['pic','gas','par','mao','eng']
  'bud':
    type:'land'
    neis:['vie','gal','rum','ser','tri']
  'bul':
    type:'coast'
    neis:['con','bla','rum','gre','ser','aeg']
    ec:['con','bla','rum']
    sc:['gre','aeg','con']
  'bur':
    type:'land'
    neis:['mar','gas','par','pic','bel','ruh','mun']
  'cly':
    type:'coast'
    neis:['edi','liv','nao','nwg']
  'con':
    type:'coast'
    neis:['bul_sc','bul_ec','ank','smy','bla','aeg']
  'den':
    type:'coast'
    neis:['swe','kie','hel','nth','bal','ska']
  'eas':
    type:'water'
    neis:['syr','smy','aeg','ion']
  'edi':
    type:'coast'
    neis:['liv','yor','cly','nth','nwg']
  'eng':
    type:'water'
    neis:['mao','iri','wal','lon','nth','bel','pic','bre']
  'fin':
    type:'coast'
    neis:['stp_sc','swe','nor','bot']
  'gal':
    type:'land'
    neis:['war','ukr','rum','bud','vie','boh','sil']
  'gas':
    type:'coast'
    neis:['spa_nc','par','bur','mar','bre','mao']
  'gre':
    type:'coast'
    neis:['bul_sc','alb','ser','aeg','ion']
  'hel':
    type:'water'
    neis:['nth','den','kie','hol']
  'hol':
    type:'coast'
    neis:['bel','kie','ruh','nth','hel']
  'ion':
    type:'water'
    neis:['tun','tys','nap','apu','adr','alb','gre','aeg','eas']
  'iri':
    type:'water'
    neis:['nao','liv','wal','eng','mao']
  'kie':
    type:'coast'
    neis:['hol','den','ber','mun','ruh','hel','bal']
  'lon':
    type:'coast'
    neis:['yor','wal','nth','eng']
  'lvn':
    type:'coast'
    neis:['stp_sc','pru','mos','war','bal','bot']
  'liv':
    type:'coast'
    neis:['wal','edi','yor','cly','iri','nao']
  'lyo':
    type:'water'
    neis:['spa_sc','mar','pie','tus','tys','wes']
  'mao':
    type:'water'
    neis:['nao','iri','eng','bre','gas','spa_nc','por','spa_sc','naf','wes']
  'mar':
    type:'coast'
    neis:['spa_sc','pie','gas','bur','lyo']
  'mos':
    type:'land'
    neis:['stp','lvn','war','ukr','sev']
  'mun':
    type:'land'
    neis:['bur','ruh','kie','ber','sil','boh','tyr']
  'naf':
    type:'coast'
    neis:['tun','mao','wes']
  'nao':
    type:'water'
    neis:['nwg','liv','iri','mao','cly']
  'nap':
    type:'coast'
    neis:['rom','apu','tys','ion']
  'nor':
    type:'coast'
    neis:['stp_nc','fin','swe','ska','nth','nwg','bar']
  'nth':
    type:'water'
    neis:['yor','edi','nwg','nor','ska','den','hel','hol','bel','eng','lon']
  'nwg':
    type:'water'
    neis:['nao','bar','nor','nth','cly','edi']
  'par':
    type:'land'
    neis:['bre','pic','bur','gas']
  'pic':
    type:'coast'
    neis:['bur','par','bre','bel','eng']
  'pie':
    type:'coast'
    neis:['mar','tus','ven','tyr','lyo']
  'por':
    type:'coast'
    neis:['spa_nc','spa_sc','mao']
  'pru':
    type:'coast'
    neis:['war','sil','ber','lvn','bal']
  'rom':
    type:'coast'
    neis:['tus','nap','ven','apu','tys']
  'ruh':
    type:'land'
    neis:['bur','bel','hol','kie','mun']
  'rum':
    type:'coast'
    neis:['bul_ec','ser','bud','gal','ukr','sev','bla']
  'ser':
    type:'land'
    neis:['tri','bud','rum','bul','gre','alb']
  'sev':
    type:'coast'
    neis:['ukr','mos','rum','arm','bla']
  'sil':
    type:'land'
    neis:['mun','ber','pru','war','gal','boh']
  'ska':
    type:'water'
    neis:['nth','nor','den','swe']
  'smy':
    type:'coast'
    neis:['syr','con','ank','arm','eas','aeg']
  'spa':
    type:'coast'
    neis:['gas','por','wes','lyo','mar','mao']
    nc:['gas','mao','por']
    sc:['por','wes','lyo','mar','mao']
  'stp':
    type:'coast'
    neis:['fin','lvn','nor','mos','bot','bar']
    nc:['bar','nor']
    sc:['fin','lvn','bot']
  'swe':
    type:'coast'
    neis:['fin','den','nor','bot','bal','ska']
  'syr':
    type:'coast'
    neis:['smy','arm','eas']
  'tri':
    type:'coast'
    neis:['tyr','vie','bud','ser','alb','ven','adr']
  'tun':
    type:'coast'
    neis:['naf','wes','tys','ion']
  'tus':
    type:'coast'
    neis:['rom','pie','ven','tys','lyo']
  'tyr':
    type:'land'
    neis:['mun','boh','vie','tri','ven','pie']
  'tys':
    type:'water'
    neis:['wes','lyo','tus','rom','nap','ion','tun']
  'ukr':
    type:'land'
    neis:['rum','gal','war','mos','sev']
  'ven':
    type:'coast'
    neis:['tyr','tus','rom','pie','apu','tri','adr']
  'vie':
    type:'land'
    neis:['tyr','boh','gal','bud','tri']
  'wal':
    type:'coast'
    neis:['liv','lon','yor','iri','eng']
  'war':
    type:'land'
    neis:['sil','pru','lvn','mos','ukr','gal']
  'wes':
    type:'water'
    neis:['spa_sc','mao','lyo','tys','tun','naf']
  'yor':
    type:'coast'
    neis:['edi','lon','liv','wal','nth']
