pid: /var/www/dip/shared/pids/thin.pid
timeout: 30
wait: 30
log: /var/www/dip/current/log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
socket: /var/www/dip/shared/thin.sock
chdir: /var/www/dip/current
tag: dip
